/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    ChatContent: typeof import('./src/components/ChatContent.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ILucideEdit: typeof import('~icons/lucide/edit')['default']
    ILucideSendHorizontal: typeof import('~icons/lucide/send-horizontal')['default']
    ILucideSquare: typeof import('~icons/lucide/square')['default']
    ILucideTextAlignJustify: typeof import('~icons/lucide/text-align-justify')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
