/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/BaseInput.vue')['default']
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    BaseSelect: typeof import('./src/components/BaseSelect.vue')['default']
    ChatContent: typeof import('./src/components/ChatContent.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    FoldButton: typeof import('./src/components/FoldButton.vue')['default']
    GeneralSettings: typeof import('./src/components/GeneralSettings.vue')['default']
    HorizontalTab: typeof import('./src/components/HorizontalTab.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    ILucideCirclePlus: typeof import('~icons/lucide/circle-plus')['default']
    ILucideCog: typeof import('~icons/lucide/cog')['default']
    ILucideEdit: typeof import('~icons/lucide/edit')['default']
    ILucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideSave: typeof import('~icons/lucide/save')['default']
    ILucideSendHorizontal: typeof import('~icons/lucide/send-horizontal')['default']
    ILucideSettings: typeof import('~icons/lucide/settings')['default']
    ILucideSquare: typeof import('~icons/lucide/square')['default']
    ILucideTextAlignJustify: typeof import('~icons/lucide/text-align-justify')['default']
    ILucideTrash2: typeof import('~icons/lucide/trash2')['default']
    MessageToast: typeof import('./src/components/MessageToast.vue')['default']
    ModelSettings: typeof import('./src/components/ModelSettings.vue')['default']
    ModelsSettings: typeof import('./src/components/ModelsSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingContent: typeof import('./src/components/SettingContent.vue')['default']
    SettingsInterface: typeof import('./src/components/SettingsInterface.vue')['default']
    SettingsWindow: typeof import('./src/components/SettingsWindow.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
